services:
  db_cashou:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-cashou_db}"
    ports:
      - "5432:5432"
    volumes:
      - cashou-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 10

  db_backoffice:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "backoffice"
    ports:
      - "5433:5432"
    volumes:
      - backoffice-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DOCKER_CONTAINER=true
      - NODE_ENV=development  # indique qu'on est en mode développement, pour activer des fonctionnalités de debug.
      - FORCE_COLOR=1 # pour forcer l'affichage des couleurs dans les logs
    env_file:
      - .env.docker
    depends_on:
      db_cashou:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      # Protect node_modules from being overwritten by local mounts
      - /app/node_modules/.prisma
      - /app/packages/@cashou/auth/node_modules
      - /app/packages/@cashou/db-app/node_modules
      - /app/packages/@cashou/db-backoffice/node_modules
      - /app/packages/@cashou/utils/node_modules
      - /app/apps/backend/node_modules
      # Protect Prisma generated files
      - /app/packages/@cashou/db-backoffice/src/generated

  backoffice:
    build:
      context: .
      dockerfile: apps/backoffice/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
      - BACKOFFICE_DB_URL=${BACKOFFICE_DB_URL}
    depends_on:
      db_backoffice:
        condition: service_healthy
    volumes:
      - ./apps/backoffice:/app/apps/backoffice
      - ./packages:/app/packages
      # Protect node_modules from being overwritten by local mounts
      - /app/node_modules/.prisma
      - /app/packages/@cashou/auth/node_modules
      - /app/packages/@cashou/db-app/node_modules
      - /app/packages/@cashou/db-backoffice/node_modules
      - /app/packages/@cashou/utils/node_modules
      - /app/apps/backoffice/node_modules
      # Protect Prisma generated files
      - /app/packages/@cashou/db-backoffice/src/generated

volumes:
  cashou-db-data:
  backoffice-db-data:
