services:
  db_cashou:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-cashou_db}"
    ports:
      - "5432:5432"
    volumes:
      - cashou-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10

  db_backoffice:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: backoffice
    ports:
      - "5433:5432"
    volumes:
      - backoffice-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      db_cashou:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages

  backoffice:
    build:
      context: .
      dockerfile: apps/backoffice/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.docker
    depends_on:
      db_backoffice:
        condition: service_healthy
    volumes:
      - ./apps/backoffice:/app/apps/backoffice
      - ./packages:/app/packages

volumes:
  cashou-db-data:
  backoffice-db-data:
