import {
  Atom,
  BarChart3,
  BookOpenCheck,
  Boxes,
  CheckSquare,
  Flame,
  History,
  Layers,
  Link2,
  Network,
  Sparkles,
  Target,
  Users,
  Workflow,
  HelpCircle,
} from 'lucide-react'
import type { BackofficeModule, ModuleConfig } from '@/lib/domain'

export const MODULE_CONFIGS: Record<BackofficeModule, ModuleConfig> = {
  levels: {
    key: 'levels',
    title: 'Niveaux',
    description: 'Structure de progression et objectifs',
    icon: Layers,
    entityName: 'Niveau',
    columns: [
      { key: 'number', label: '#', width: '40px' },
      { key: 'title', label: 'Titre' },
      { key: 'duration', label: 'Durée (jours)', width: '140px' },
      { key: 'speed', label: 'Vitesse', width: '120px' },
      { key: 'startBalance', label: 'Balance initiale', width: '160px' },
      { key: 'pointsRequired', label: 'Points requis', width: '140px' },
    ],
    fields: [
      { key: 'title', label: 'Titre', type: 'text', placeholder: 'Découverte', required: true },
      { key: 'number', label: 'Ordre', type: 'number', placeholder: '1', required: true },
      { key: 'duration', label: 'Durée (jours)', type: 'number', placeholder: '14' },
      { key: 'speed', label: 'Vitesse', type: 'number', placeholder: '1' },
      {
        key: 'startBalance',
        label: 'Balance initiale',
        type: 'number',
        placeholder: '10000',
        helperText: 'Capital fictif de départ',
      },
      {
        key: 'pointsRequired',
        label: 'Points requis',
        type: 'number',
        placeholder: '500',
      },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Objectifs...' },
    ],
  },
  goals: {
    key: 'goals',
    title: 'Objectifs',
    description: 'Définition des missions par niveau',
    icon: Target,
    entityName: 'Objectif',
    columns: [
      { key: 'title', label: 'Nom' },
      { key: 'description', label: 'Description' },
      { key: 'type', label: 'Type', width: '120px' },
    ],
    fields: [
      { key: 'title', label: 'Nom', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'type', label: 'Type', type: 'text', placeholder: 'progression, KPI…' },
      { key: 'kpi', label: 'KPI associé', type: 'text' },
    ],
  },
  markets: {
    key: 'markets',
    title: 'Marchés',
    description: 'Stratégie Macro & tendances',
    icon: Target,
    entityName: 'Marché',
    columns: [
      { key: 'title', label: 'Nom' },
      {
        key: 'description',
        label: 'Narratif',
        render: (record) => (record.description as string | undefined)?.slice(0, 64) ?? '',
      },
      {
        key: 'submarkets',
        label: 'Sous-marchés',
        width: '140px',
        render: (record) => (Array.isArray(record.submarkets) ? record.submarkets.length : 0),
      },
      {
        key: 'assets',
        label: 'Actifs',
        width: '120px',
        render: (record) => (Array.isArray(record.assets) ? record.assets.length : 0),
      },
      {
        key: 'fields',
        label: 'Champs',
        width: '120px',
        render: (record) => (Array.isArray(record.fields) ? record.fields.length : 0),
      },
    ],
    fields: [
      { key: 'title', label: 'Nom du marché', type: 'text', required: true },
      { key: 'description', label: 'Narratif', type: 'textarea', placeholder: 'Why now ?' },
    ],
  },
  submarkets: {
    key: 'submarkets',
    title: 'Sous-marchés',
    description: 'Segments tactiques',
    icon: Workflow,
    entityName: 'Sous-marché',
    columns: [
      { key: 'title', label: 'Nom' },
      { key: 'description', label: 'Narratif' },
      { key: 'marketId', label: 'Marché', width: '160px' },
      {
        key: 'assets',
        label: 'Actifs',
        width: '120px',
        render: (record) => (Array.isArray(record.assets) ? record.assets.length : 0),
      },
    ],
    fields: [
      { key: 'title', label: 'Nom', type: 'text', required: true },
      { key: 'description', label: 'Narratif', type: 'textarea' },
      { key: 'marketId', label: 'Marché parent', type: 'select', required: true },
    ],
  },
  fields: {
    key: 'fields',
    title: 'Champs',
    description: 'Domaines disciplinaires',
    icon: Atom,
    entityName: 'Champ',
    columns: [
      { key: 'name', label: 'Nom' },
      { key: 'marketId', label: 'Marché', width: '180px' },
      { key: 'updatedAt', label: 'Mise à jour', width: '160px' },
    ],
    fields: [
      { key: 'name', label: 'Nom', type: 'text', required: true },
      { key: 'marketId', label: 'Marché lié', type: 'select' },
    ],
  },
  assets: {
    key: 'assets',
    title: 'Actifs',
    description: 'Produits, entreprises ou tokens suivis',
    icon: Boxes,
    entityName: 'Actif',
    columns: [
      { key: 'symbol', label: 'Ticker', width: '90px' },
      { key: 'title', label: 'Nom' },
      { key: 'field', label: 'Champ', width: '140px' },
      { key: 'marketId', label: 'Marché', width: '160px' },
      { key: 'submarketId', label: 'Sous-marché', width: '160px' },
    ],
    fields: [
      { key: 'symbol', label: 'Ticker', type: 'text', required: true },
      { key: 'title', label: 'Nom', type: 'text', required: true },
      { key: 'field', label: 'Champ disciplinaire', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'marketId', label: 'Marché', type: 'select' },
      { key: 'submarketId', label: 'Sous-marché', type: 'select' },
    ],
  },
  events: {
    key: 'events',
    title: 'Événements',
    description: 'Scénarios macro & signaux terrain',
    icon: BarChart3,
    entityName: 'Événement',
    columns: [
      { key: 'title', label: 'Nom' },
      {
        key: 'hasImpact',
        label: 'Impact',
        width: '120px',
        render: (record) => ((record.hasImpact as boolean) ? 'Oui' : 'À qualifier'),
      },
      { key: 'description', label: 'Description' },
    ],
    fields: [
      { key: 'title', label: 'Nom', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'hasImpact', label: 'Impact identifié', type: 'checkbox' },
    ],
  },
  quizzes: {
    key: 'quizzes',
    title: 'Quizz',
    description: 'Gestion des quizz Daily et MCQ',
    icon: BookOpenCheck,
    entityName: 'Quiz',
    columns: [
      { key: 'title', label: 'Titre' },
      { key: 'type', label: 'Type', width: '120px' },
      { key: 'levelId', label: 'Niveau', width: '120px' },
      { key: 'date', label: 'Date', width: '160px' },
    ],
    fields: [
      { key: 'title', label: 'Titre', type: 'text', required: true },
      { key: 'description', label: 'Narratif', type: 'textarea' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        valueType: 'string',
        helperText: 'DAILY ou MCQ',
        options: [
          { label: 'Daily', value: 'DAILY' },
          { label: 'MCQ', value: 'MCQ' },
        ],
      },
      { key: 'levelId', label: 'Associer à un niveau', type: 'number' },
      { key: 'date', label: 'Date', type: 'date' },
    ],
  },
  questions: {
    key: 'questions',
    title: 'Questions',
    description: 'Banque de questions',
    icon: HelpCircle,
    entityName: 'Question',
    columns: [
      { key: 'text', label: 'Intitulé' },
      { key: 'difficulty', label: 'Difficulté', width: '120px' },
    ],
    fields: [
      { key: 'text', label: 'Question', type: 'textarea', required: true },
      { key: 'difficulty', label: 'Difficulté', type: 'text', placeholder: 'easy / medium / hard' },
      { key: 'category', label: 'Catégorie', type: 'text' },
    ],
  },
  answers: {
    key: 'answers',
    title: 'Réponses',
    description: 'Réponses possibles et validation',
    icon: CheckSquare,
    entityName: 'Réponse',
    columns: [
      { key: 'questionId', label: 'Question', width: '140px' },
      { key: 'text', label: 'Réponse' },
      {
        key: 'isCorrect',
        label: 'Correcte',
        width: '100px',
        render: (record) => ((record.isCorrect as boolean) ? '✅' : '—'),
      },
    ],
    fields: [
      { key: 'questionId', label: 'Question', type: 'select', required: true },
      { key: 'text', label: 'Réponse', type: 'textarea', required: true },
      { key: 'isCorrect', label: 'Bonne réponse', type: 'checkbox' },
    ],
  },
  levelGoals: {
    key: 'levelGoals',
    title: 'Liens Niveau ↔ Objectif',
    description: 'Associez plusieurs objectifs à un niveau',
    icon: Link2,
    entityName: 'Lien objectif',
    columns: [
      { key: 'levelId', label: 'Niveau', width: '120px' },
      { key: 'goalId', label: 'Objectif', width: '160px' },
    ],
    fields: [
      { key: 'levelId', label: 'Niveau', type: 'select', required: true },
      { key: 'goalId', label: 'Objectif', type: 'select', required: true },
    ],
  },
  levelEvents: {
    key: 'levelEvents',
    title: 'Liens Niveau ↔ Événement',
    description: 'Définissez les événements déclenchés à chaque niveau',
    icon: Sparkles,
    entityName: 'Lien événement',
    columns: [
      { key: 'levelId', label: 'Niveau', width: '120px' },
      { key: 'eventId', label: 'Événement', width: '160px' },
    ],
    fields: [
      { key: 'levelId', label: 'Niveau', type: 'select', required: true },
      { key: 'eventId', label: 'Événement', type: 'select', required: true },
    ],
  },
  quizQuestions: {
    key: 'quizQuestions',
    title: 'Quizz ↔ Questions',
    description: 'Ordonnancer les questions d’un quiz',
    icon: Layers,
    entityName: 'Lien quiz',
    columns: [
      { key: 'quizId', label: 'Quiz', width: '120px' },
      { key: 'questionId', label: 'Question', width: '160px' },
      { key: 'order', label: 'Ordre', width: '80px' },
    ],
    fields: [
      { key: 'quizId', label: 'Quiz', type: 'select', required: true },
      { key: 'questionId', label: 'Question', type: 'select', required: true },
      { key: 'order', label: 'Ordre', type: 'number' },
    ],
  },
  assetHistory: {
    key: 'assetHistory',
    title: 'Historique actifs',
    description: 'Valeurs & volumes',
    icon: History,
    entityName: 'Historique',
    columns: [
      { key: 'assetId', label: 'Actif', width: '140px' },
      { key: 'timestamp', label: 'Date', width: '160px' },
      { key: 'value', label: 'Valeur', width: '120px' },
      { key: 'volume', label: 'Volume', width: '120px' },
    ],
    fields: [
      { key: 'assetId', label: 'Actif', type: 'select', required: true },
      { key: 'timestamp', label: 'Date', type: 'date', required: true },
      { key: 'value', label: 'Valeur', type: 'number', required: true },
      { key: 'volume', label: 'Volume', type: 'number', required: true },
    ],
  },
  eventAsset: {
    key: 'eventAsset',
    title: 'Event x Asset',
    description: 'Propagation des événements',
    icon: Network,
    entityName: 'Couplage',
    columns: [
      { key: 'eventId', label: 'Événement', width: '160px' },
      { key: 'assetId', label: 'Actif', width: '140px' },
      { key: 'date', label: 'Date', width: '140px' },
      { key: 'value', label: 'Valeur', width: '120px' },
      { key: 'volume', label: 'Volume', width: '120px' },
    ],
    fields: [
      { key: 'eventId', label: 'Événement', type: 'select', required: true },
      { key: 'assetId', label: 'Actif', type: 'select', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'value', label: 'Valeur', type: 'number' },
      { key: 'volume', label: 'Volume', type: 'number' },
    ],
  },
  impacts: {
    key: 'impacts',
    title: 'Impacts',
    description: 'Modélisation des causalités',
    icon: Flame,
    entityName: 'Impact',
    columns: [
      { key: 'eventId', label: 'Événement', width: '160px' },
      { key: 'fieldId', label: 'Champ', width: '140px' },
      { key: 'submarketId', label: 'Sous-marché', width: '140px' },
      { key: 'coef', label: 'Coefficient', width: '140px' },
    ],
    fields: [
      { key: 'eventId', label: 'Événement', type: 'select', required: true },
      { key: 'fieldId', label: 'Champ', type: 'select' },
      { key: 'submarketId', label: 'Sous-marché', type: 'select' },
      { key: 'coef', label: 'Coefficient', type: 'number', required: true },
    ],
  },
  players: {
    key: 'players',
    title: 'Joueurs & Parties',
    description: 'Suivi temps réel des sessions utilisateurs',
    icon: Users,
    entityName: 'Joueur',
  },
}

export const ORDERED_MODULES: BackofficeModule[] = [
  'levels',
  'goals',
  'levelGoals',
  'levelEvents',
  'quizzes',
  'questions',
  'answers',
  'quizQuestions',
  'markets',
  'submarkets',
  'fields',
  'assets',
  'events',
  'assetHistory',
  'eventAsset',
  'impacts',
  'players',
]
